# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: bored-ape-yacht-club-nft-indexer
unordered_multichain_mode: true
networks:
  - id: 1
    start_block: 12292921
    end_block: 12342921 # first 50,000 blocks
    contracts:
      - name: BoredApeYachtClub
        address:
          - 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D
        handler: src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
